USE sdgc;
UPDATE centroeducativo SET estado = 'ACTIVO' where id > 0;
UPDATE denuncia SET estado = 'ACTIVO' where id > 0;
UPDATE derecho SET estado = 'ACTIVO' where id > 0;
UPDATE domicilio SET estado = 'ACTIVO' where id > 0;
UPDATE junta SET estado = 'ACTIVO' where id > 0;
UPDATE persona SET estado = 'ACTIVO' where id > 0;
UPDATE personadomicilio SET estado = 'ACTIVO' where id > 0;
UPDATE vulnerado SET estado = 'ACTIVO' where id > 0;
UPDATE vulneradodomicilio SET estado = 'ACTIVO' where id > 0;
