# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
 
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    ~
 
    #ROLES: ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN
    #If you make sure that no users ever have ROLE_NO_ACCESS, then access is denied 
    #(ROLE_NO_ACCESS can be anything that does not match an existing role, it just serves as a trick to always deny access).
    
    access_control:
        #centroEducativo        
        - { path: /centroEducativo/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /centroEducativo/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /centroEducativo/guardar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /centroEducativo/eliminar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        #derecho
        - { path: /derecho/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /derecho/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /derecho/guardar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        - { path: /derecho/eliminar, roles: [ROLE_SUPER_ADMIN] }
        #denuncia
        - { path: /denuncia/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /denuncia/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /denuncia/guardar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /denuncia/eliminar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        #auditoria
        - { path: /auditoria/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /auditoria/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /auditoria/guardar, roles: ROLE_NO_ACCESS }
        - { path: /auditoria/eliminar, roles: ROLE_NO_ACCESS }
        #junta
        - { path: /junta/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /junta/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /junta/guardar, roles: [ROLE_SUPER_ADMIN] }
        - { path: /junta/eliminar, roles: [ROLE_SUPER_ADMIN] }
        #provincia
        - { path: /provincia/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /provincia/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /provincia/guardar, roles: [ROLE_SUPER_ADMIN] }
        - { path: /provincia/eliminar, roles: [ROLE_SUPER_ADMIN] }
        #canton
        - { path: /canton/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /canton/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /canton/guardar, roles: [ROLE_SUPER_ADMIN] }
        - { path: /canton/eliminar, roles: [ROLE_SUPER_ADMIN] }
        #parroquia
        - { path: /parroquia/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /parroquia/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /parroquia/guardar, roles: [ROLE_SUPER_ADMIN] }
        - { path: /parroquia/eliminar, roles: [ROLE_SUPER_ADMIN] }
        #usuario
        - { path: /usuario/listar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        - { path: /usuario/mostrar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        - { path: /usuario/guardar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        - { path: /usuario/eliminar, roles: [ROLE_SUPER_ADMIN] }
        #comando
        - { path: /comando/*, roles: ROLE_SUPER_ADMIN }
        #actividadEconomica        
        - { path: /actividadEconomica/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /actividadEconomica/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /actividadEconomica/guardar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /actividadEconomica/eliminar, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN_JUNTA] }
        #actor        
        - { path: /actor/listar, roles: [ROLE_NO_ACCESS] }
        - { path: /actor/mostrar, roles: [ROLE_NO_ACCESS] }
        - { path: /actor/guardar, roles: [ROLE_NO_ACCESS] }
        - { path: /actor/eliminar, roles: [ROLE_NO_ACCESS] }
        #actorDireccion        
        - { path: /actorDireccion/listar, roles: [ROLE_NO_ACCESS] }
        - { path: /actorDireccion/mostrar, roles: [ROLE_NO_ACCESS] }
        - { path: /actorDireccion/guardar, roles: [ROLE_NO_ACCESS] }
        - { path: /actorDireccion/eliminar, roles: [ROLE_NO_ACCESS] }
        #archivo        
        - { path: /archivo/listar, roles: [ROLE_NO_ACCESS] }
        - { path: /archivo/mostrar, roles: [ROLE_NO_ACCESS] }
        - { path: /archivo/guardar, roles: [ROLE_NO_ACCESS] }
        - { path: /archivo/eliminar, roles: [ROLE_NO_ACCESS] }
        #direccion        
        - { path: /direccion/listar, roles: [ROLE_NO_ACCESS] }
        - { path: /direccion/mostrar, roles: [ROLE_NO_ACCESS] }
        - { path: /direccion/guardar, roles: [ROLE_NO_ACCESS] }
        - { path: /direccion/eliminar, roles: [ROLE_NO_ACCESS] }
        #operacionDenuncia        
        - { path: /operacionDenuncia/listar, roles: [ROLE_NO_ACCESS] }
        - { path: /operacionDenuncia/mostrar, roles: [ROLE_NO_ACCESS] }
        - { path: /operacionDenuncia/guardar, roles: [ROLE_NO_ACCESS] }
        - { path: /operacionDenuncia/eliminar, roles: [ROLE_NO_ACCESS] }
        #plantilla        
        - { path: /plantilla/listar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /plantilla/mostrar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /plantilla/guardar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        - { path: /plantilla/eliminar, roles: [ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMIN_JUNTA, ROLE_SUPER_ADMIN] }
        
        
    role_hierarchy:
        ROLE_SECRETARIO:     [ROLE_USER]
        ROLE_MIEMBRO_DE_JUNTA:     [ROLE_USER]
        ROLE_PSICOLOGO:     [ROLE_USER]
        ROLE_ADMIN_JUNTA:       [ROLE_USER, ROLE_SECRETARIO, ROLE_MIEMBRO_DE_JUNTA, ROLE_PSICOLOGO, ROLE_ADMINISTRAR_JUNTA]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN_JUNTA, ROLE_CONFIGURAR_JUNTA]