# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.form.registration:
       class: AppBundle\Form\UsuarioType
       tags:
           - { name: form.type, alias: app_user_registration }
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu_builder, method: createAdminDeJuntaMenu, alias: adminDeJunta } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createLoginMenu, alias: login } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createSecretarioMenu, alias: secretario } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createMiembroDeJuntaMenu, alias: miembroDeJunta } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createPsicologoMenu, alias: psicologo } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createSuperAdminMenu, alias: superAdmin } # The alias is what is used to retrieve the menu
            

    app.form.type.direccion:
        class: AppBundle\Form\DireccionType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
            
    app.form.type.centroeducativo:
        class: AppBundle\Form\CentroEducativoTodoType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    app.redirect_after_registration_subscriber:
        class: AppBundle\EventListener\RedirectAfterRegistrationSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
    security.interactive_login.listener:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            
    # authentication failure event listener
    app.security.authentication_event_listener:
        class: AppBundle\EventListener\LoginListener
        arguments: [fos_user.user_manager,session]
        tags:
            - { name: kernel.event_subscriber }